# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-28 22:03
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('EE', 'Electrical Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('ECE', 'Electronics and Communication'), ('IC', 'Instrumentation and Control'), ('CE', 'Civil Engineering'), ('Select Branch', 'Select Branch')], default='Select Branch', max_length=20)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('ALL', 'ALL'), ('Select Year', 'Select Year')], default='Select Year', max_length=5)),
                ('subject', models.CharField(choices=[('DSGT', 'DSGT'), ('DS', 'DS'), ('MATHS3', 'MATHS3'), ('CBNST', 'CBNST'), ('OS', 'OS'), ('MUL', 'MUL'), ('TOFL', 'TOFL'), ('Select Subject', 'Select Subject')], default='Select Subject', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('question', ckeditor.fields.RichTextField()),
                ('marks', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('n_used', models.IntegerField(default=0)),
                ('co', models.IntegerField(default=1)),
                ('imp', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
