# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-26 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('EE', 'Electrical Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('ECE', 'Electronics and Communication'), ('IC', 'Instrumentation and Control'), ('CE', 'Civil Engineering'), ('Select Branch', 'Select Branch')], default='Select Branch', max_length=20)),
                ('year', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), ('ALL', 'ALL'), ('Select Year', 'Select Year')], default='Select Year', max_length=5)),
                ('subject', models.CharField(choices=[('DSGT', 'DSGT'), ('DS', 'DS'), ('MATHS3', 'MATHS3'), ('CBNST', 'CBNST'), ('OS', 'OS'), ('MUL', 'MUL'), ('TOFL', 'TOFL'), ('Select Subject', 'Select Subject')], default='Select Subject', max_length=12)),
            ],
        ),
    ]
