# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-26 20:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondetail',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
