# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-29 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_questiondetail_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondetail',
            name='branch',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
