# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_activesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondetail',
            name='co',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='filter',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('ALL', 'ALL'), ('Select Year', 'Select Year')], default='Select Year', max_length=5),
        ),
        migrations.AlterField(
            model_name='questiondetail',
            name='n_used',
            field=models.IntegerField(default=0),
        ),
    ]
